### ISSUE TITLE
The label of the emotion "Compassion".

### ISSUE THREAD

**Issue by JONHYOJIN** [SalvoCalcagno/eeg-music-challenge-icassp-2025-baselines#2]
Hi, I have a question regarding the label assigned to the emotion "Compassion."

After reviewing the emotion coordinates and labels across the entire dataset, I found that most emotions are consistently aligned with one of the four categories: HVHD (0), HVLD (1), LVLD (2), and LVHD (3). However, I noticed that "Compassion" is assigned the label "HVLD (1)" despite its coordinates indicating it should fall under "LVLD (2)."

Could you clarify if this alignment was intentional and, if so, provide the reasoning behind it? If this is an error, I’d appreciate any insights into a possible correction. Thank you!

**Comment by SalvoCalcagno** [comment]
Thank you for bringing this up. We use this version of the emotion wheel:
![image](https://github.com/user-attachments/assets/e99c532a-1243-4213-bb73-466f79cbb01a)

According to the guidelines from [University of Geneva](https://www.unige.ch/cisa/gew), we divide the wheel into four equally distributed sections and assign labels to each sector. Then, "Compassion" still falls within class 1.

Coordinates for each emotion are referenced from a separate study.
For a deeper understanding of the coordinates, you may consult: Scherer, Klaus R., et al., “The GRID meets the Wheel: Assessing emotional feeling via self-report,” in Components of Emotional Meaning: A sourcebook (ed. Johnny J. R. Fontaine, Klaus R. Scherer, Cristina Soriano), Oxford University Press, 2013. Available online at Oxford Academic: [https://doi.org/10.1093/acprof](https://doi.org/10.1093/acprof:oso/9780199592746.003.0019)
[/9780199592746.003.0019](https://doi.org/10.1093/acprof:oso/9780199592746.003.0019), accessed on 11 Nov. 2024.
